ex8:
	mpicc ex8.c -o ex8.out
	mpiexec -np 2 ex8.out

ex9a:
	mpicc ex9a.c -o ex9a.out
	mpiexec -np 2 ex9a.out

ex9b:
	mpicc ex9b.c -o ex9b.out
	mpiexec -np 3 ex9b.out

ex10a:
	mpicc ex10a.c -o ex10a.out
	mpiexec -np 4 ex10a.out

ex10b:
	mpicc ex10b.c -o ex10b.out
	mpiexec -np 4 ex10b.out

ex10c:
	mpicc ex10c.c -o ex10c.out
	mpiexec -np 4 ex10c.out