q1:
	gcc q1_dynamic.c -fopenmp -o q1_dynamic.out
	./q1_dynamic.out 32 10
	./q1_dynamic.out 64 10
	./q1_dynamic.out 128 10
	./q1_dynamic.out 32 20
	./q1_dynamic.out 64 20
	./q1_dynamic.out 128 20
	./q1_dynamic.out 32 50
	./q1_dynamic.out 64 50
	./q1_dynamic.out 128 50
	gcc q1_others.c -fopenmp -o q1_others.out
	./q1_others.out 32
	./q1_others.out 64
	./q1_others.out 128

q2:
	gcc q2.c -fopenmp -o q2.out
	./q2.out
