q1:
	gcc q1.c -fopenmp -o q1.out
	./q1.out
q2:
	gcc q2.c -fopenmp -o q2.out
	./q2.out 4 1
	./q2.out 8 1
	./q2.out 16 1
	./q2.out 4 2
	./q2.out 8 2
	./q2.out 16 2
	./q2.out 4 3
	./q2.out 8 3
	./q2.out 16 3
	./q2.out 4 4
	./q2.out 8 4
	./q2.out 16 4

q2_1:
	gcc q2.c -fopenmp -o q2.out
	./q2.out 4 0
	./q2.out 4 1
	./q2.out 4 2
	./q2.out 4 3
	./q2.out 4 4